import { create } from "zustand";

const useFormState = create((set) => ({
  table1No1: "",
  table1Amt1: "",
  table1No2: "",
  table1Amt2: "",
  table1No3: "",
  table1Amt3: "",
  table1No4: "",
  table1Amt4: "",
  table1No5: "",
  table1Amt5: "",
  No: "",
  date: "",
  received: "",
  tin: "",
  address: "",
  businessStyle: "",
  sumPesos: "",
  pesos: 0,
  paymentFor: "",
  selected: "",
  table2Price1: "",
  table2Amt1: "",
  table2Price2: "",
  table2Amt2: "",
  table2Price3: "",
  table2Amt3: "",
  table2Price4: "",
  table2Amt4: "",
  table2Price5: "",
  table2Amt5: "",

  //Reducers
  setTable1No1: (value) => set({ table1No1: value }),
  setTable1Amt1: (value) => set({ table1Amt1: value }),
  setTable1No2: (value) => set({ table1No2: value }),
  setTable1Amt2: (value) => set({ table1Amt2: value }),
  setTable1No3: (value) => set({ table1No3: value }),
  setTable1Amt3: (value) => set({ table1Amt3: value }),
  setTable1No4: (value) => set({ table1No4: value }),
  setTable1Amt4: (value) => set({ table1Amt4: value }),
  setTable1No5: (value) => set({ table1No5: value }),
  setTable1Amt5: (value) => set({ table1Amt5: value }),
  setNo: (value) => set({ No: value }),
  setDate: (value) => set({ date: value }),
  setReceived: (value) => set({ received: value }),
  setTin: (value) => set({ tin: value }),
  setAddress: (value) => set({ address: value }),
  setBusinessStyle: (value) => set({ businessStyle: value }),
  setSum: (value) => set({ sumPesos: value }),
  setPesos: (value) => set({ pesos: value }),
  setPaymentFor: (value) => set({ paymentFor: value }),
  setSelected : (value) =>set({selected: value}),
  setTable2Price1 : (value)=>set({table2Price1: value}),
  setTable2Amt1: (value)=>set({table2Amt1: value}),
  setTable2Price2 : (value)=>set({table2Price2: value}),
  setTable2Amt2: (value)=>set({table2Amt2: value}),
  setTable2Price3 : (value)=>set({table2Price3: value}),
  setTable2Amt3: (value)=>set({table2Amt3: value}),
  setTable2Price4 : (value)=>set({table2Price4: value}),
  setTable2Amt4: (value)=>set({table2Amt4: value}),
  setTable2Price5 : (value)=>set({table2Price5: value}),
  setTable2Amt5: (value)=>set({table2Amt5: value}),
}));

export { useFormState };
